# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Algorhythm' do
  pod 'BMSCore', '~> 2.6.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'MessageKit', '~> 0.13'
      pod 'IBMWatsonAssistantV1', '~> 3.5.0'
      pod 'NVActivityIndicatorView', '~> 4.8.0'

      post_install do |installer|
          installer.pods_project.targets.each do |target|
              if ['SwiftCloudant'].include? target.name
                  target.build_configurations.each do |config|
                      config.build_settings['SWIFT_VERSION'] = '3.2'
                  end
              end
          end
      end
  
  # Pods for Algorhythm

  target 'AlgorhythmTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AlgorhythmUITests' do
    # Pods for testing
  end

end
