# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Algorhythm' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Algorhythm

  target 'AlgorhythmTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AlgorhythmUITests' do
    # Pods for testing
  end

end
